name: "Build"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    outputs:
      version: ${{ steps.set_proj_version.outputs.PKG_VERSION }}
      relnotes: ${{ steps.set_proj_version.outputs.RELNOTES }}
    name: Build and package 
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm
      PROJECT_PATH: "src/dotnetdumpall/dotnetdumpall.csproj"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: üß∞ Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    # NOTE: this echo hack is due to https://github.com/dotnet/sdk/issues/10310
    - name: üß∞ Install NBGV
      run: dotnet tool install -g nbgv | echo "already installed"

    - name: ‚òÄÔ∏è Set Version
      run: nbgv cloud
      
    - name: ‚ôªÔ∏è Restore
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: üèóÔ∏è Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - name: üíº Pack
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release -o finalpackage --no-build

    - name: ‚¨ÜÔ∏è Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: nupkg
        path: finalpackage

    - name: Get version
      id: set_proj_version
      shell: pwsh
      run: |
        [xml]$nuspec = Get-Content ${{ env.PROJECT_PATH }}
        $nbgv = nbgv get-version -f json | ConvertFrom-Json
        $version=$nbgv.NuGetPackageVersion
        $relnotes=$nuspec.project.propertygroup.packagereleasenotes
        Add-Content -Path $env:GITHUB_OUTPUT -Value "PKG_VERSION=$version"
        Add-Content -Path $env:GITHUB_OUTPUT -Value "RELNOTES=$relnotes"

  deploy:
    needs: build
    environment:
      name: production
      url: https://www.nuget.org/packages/TimHeuer.DumpAll
    name: Sign and publish
    runs-on: ubuntu-latest # using windows agent due to nuget can't sign on linux yet
    permissions:
      contents: write
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm
    steps:
      - name: ‚¨áÔ∏è Download Package artifact
        uses: actions/download-artifact@v3
        with:
          name: nupkg

      - name: üß∞ Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: üîê Get certificate
        id: cert_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'certfile.pfx'
          encodedString: ${{ secrets.SIGNING_CERT }}
      
      - name: ‚úçÔ∏è Sign NuGet Package
        run: dotnet nuget sign **/*.nupkg --certificate-path ${{ steps.cert_file.outputs.filePath }} --certificate-password ${{ secrets.CERT_PWD }} --timestamper http://timestamp.digicert.com
      
      - name: üëá Push to NuGet
        run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: üè∑Ô∏è Tag and Release
        id: tag_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          body: ${{ needs.build.outputs.relnotes }}
          tag_name: ${{ needs.build.outputs.version }}
          generate_release_notes: true
          files: |
            **/*.nupkg

      - name: ‚¨ÜÔ∏è Publish signed artifact
        uses: actions/upload-artifact@v3
        with:
          name: signednupkg
          path: .